### ISSUE TITLE
LoggingPerMinTask could be re-arranged

### ISSUE THREAD

**Issue by SummerWish** [SummerWish/Tahiti#6]
It can be arranged inside the scope of `Logging` class, e.g, constructor, instead of occupy another slot in `Console`.

**Comment by HermanZzz** [comment]
Got it!

**Comment by SummerWish** [comment]
What's the progress?

**Comment by HermanZzz** [comment]
As for client, I cannot find corresponding `event` or methods to `@Subscribe`. Do I need to add events or modify the current event? For example, to log the number of messages client sent, I cannot find out weather the message is sent successfully by `@Subcribe`  `client.event.MessageEvent`.

**Comment by SummerWish** [comment]
Yes, you need to add event classes and raise events by yourself.
